# This is an example of Drone 1.0 pipeline
#
# Please check https://github.com/Toroid-io/drone-kicad for the full
# plugin documentation

kind: pipeline
name: default

steps:
- name: sample-build
  image: toroid/drone-kicad:0.5.5       # drone-kicad plugin
  pull: true                            # always use latest image
  settings:
    projects:
      - main: drone-kicad-sample          # out first project, relative path, no extension
        dependencies:                     # clone dependencies in default path (/usr/share/kicad)
          libraries:
            - https://github.com/Toroid-io/toroid-kicad-library.git
          templates:
            - https://github.com/Toroid-io/toroid-kicad-templates.git
          svglib:
            - https://github.com/yaqwsx/PcbDraw-Lib
          svglibdirs:
            - PcbDraw-Lib/KiCAD-base
        options:                          # main PCB options
          bom: true                       # XML and CSV BOM
          svg: true                       # SVG board plot
          grb:
            all: true                     # generate all gerber files
          sch: true                       # export schematic in pdf
          tags:
            all: true                     # tag board with date, commit SHA and tag if any
        variants:
          - name: "Variant_1"             # name, used to postfix the variant
            content: "sample1"            # this will match the "variant" field in components
            options:                      # same as for the main PCB
              tags:
                all: true
              svg: true
              pcb: true                   # export the variant PCB file
              grb:
                all: true
          - name: "Variant_2"
            content: "sample2"
            options:
              svg: true
              pcb: true
              tags:
                all: true
              grb:
                all: true
          - name: "Variant_3"
            content: "sample3"
            options:
              tags:
                all: true
              svg: true
              pcb: true
              grb:
                all: true

- name: deploy
  image: toroid/drone-mella
  settings:
    server: https://cloud.toroid.io
    remote_folder: "drone-kicad-sample"
    parentdir: false
    files:
      - "CI-BUILD/*"
  when:
    event: push
    branch: master                      # only deploy on master branch
    status: [success, failure]
  environment:
    MELLA_USERNAME:
      from_secret: mella_username
    MELLA_PASSWORD:
      from_secret: mella_password
